
package info.java.tips.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IndicatorEndpointService", targetNamespace = "http://www.example.org/User", wsdlLocation = "http://localhost:8081/soap-api/solicita-ws?wsdl")
public class IndicatorEndpointService
    extends Service
{

    private final static URL INDICATORENDPOINTSERVICE_WSDL_LOCATION;
    private final static WebServiceException INDICATORENDPOINTSERVICE_EXCEPTION;
    private final static QName INDICATORENDPOINTSERVICE_QNAME = new QName("http://www.example.org/User", "IndicatorEndpointService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/soap-api/solicita-ws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INDICATORENDPOINTSERVICE_WSDL_LOCATION = url;
        INDICATORENDPOINTSERVICE_EXCEPTION = e;
    }

    public IndicatorEndpointService() {
        super(__getWsdlLocation(), INDICATORENDPOINTSERVICE_QNAME);
    }

    public IndicatorEndpointService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INDICATORENDPOINTSERVICE_QNAME, features);
    }

    public IndicatorEndpointService(URL wsdlLocation) {
        super(wsdlLocation, INDICATORENDPOINTSERVICE_QNAME);
    }

    public IndicatorEndpointService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INDICATORENDPOINTSERVICE_QNAME, features);
    }

    public IndicatorEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IndicatorEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CadastroPortType
     */
    @WebEndpoint(name = "cadastro_PortTypePort")
    public CadastroPortType getCadastroPortTypePort() {
        return super.getPort(new QName("http://www.example.org/User", "cadastro_PortTypePort"), CadastroPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CadastroPortType
     */
    @WebEndpoint(name = "cadastro_PortTypePort")
    public CadastroPortType getCadastroPortTypePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/User", "cadastro_PortTypePort"), CadastroPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INDICATORENDPOINTSERVICE_EXCEPTION!= null) {
            throw INDICATORENDPOINTSERVICE_EXCEPTION;
        }
        return INDICATORENDPOINTSERVICE_WSDL_LOCATION;
    }

}
